In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("Weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,217,Aksarka,66.56,67.80,0.27,94,91,4.32,RU,11/9/2019 18:32
1,263,Srednekolymsk,67.46,153.71,1.38,95,100,9.40,RU,11/9/2019 18:23
2,34,Dikson,73.51,80.55,1.63,96,77,5.59,RU,11/9/2019 18:22
3,164,Labytnangi,66.66,66.39,1.78,92,98,5.37,RU,11/9/2019 18:27
4,177,Magdagachi,53.45,125.80,2.53,95,68,4.41,RU,11/9/2019 18:32

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [4]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 70

In [9]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,217,Aksarka,66.56,67.80,0.27,94,91,4.32,RU,11/9/2019 18:32
1,263,Srednekolymsk,67.46,153.71,1.38,95,100,9.40,RU,11/9/2019 18:23
2,34,Dikson,73.51,80.55,1.63,96,77,5.59,RU,11/9/2019 18:22
3,164,Labytnangi,66.66,66.39,1.78,92,98,5.37,RU,11/9/2019 18:27
4,177,Magdagachi,53.45,125.80,2.53,95,68,4.41,RU,11/9/2019 18:32
5,37,Inuvik,68.36,-133.71,3.20,77,20,10.29,CA,11/9/2019 18:31
6,42,Thompson,55.74,-97.86,3.20,77,75,6.93,CA,11/9/2019 18:22
7,96,Tuktoyaktuk,69.44,-133.03,3.20,77,20,17.22,CA,11/9/2019 18:22
8,326,Aklavik,68.22,-135.01,3.20,77,20,14.99,CA,11/9/2019 18:27
9,317,Motygino,58.18,94.69,3.49,92,100,9.19,RU,11/9/2019 18:32

In [10]:
preferred_cities_df.count()

City_ID       316
City          316
Lat           316
Lng           316
Max Temp      316
Humidity      316
Cloudiness    316
Wind Speed    316
Country       314
Date          316
dtype: int64

In [11]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp    Lat     Lng Hotel Name
0        Aksarka      RU      0.27  66.56   67.80
1  Srednekolymsk      RU      1.38  67.46  153.71
2         Dikson      RU      1.63  73.51   80.55
3     Labytnangi      RU      1.78  66.66   66.39
4     Magdagachi      RU      2.53  53.45  125.80
5         Inuvik      CA      3.20  68.36 -133.71
6       Thompson      CA      3.20  55.74  -97.86
7    Tuktoyaktuk      CA      3.20  69.44 -133.03
8        Aklavik      CA      3.20  68.22 -135.01
9       Motygino      RU      3.49  58.18   94.69

In [12]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [13]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [14]:
hotel_df.head(20)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Aksarka,RU,0.27,66.56,67.80,
1,Srednekolymsk,RU,1.38,67.46,153.71,
2,Dikson,RU,1.63,73.51,80.55,
3,Labytnangi,RU,1.78,66.66,66.39,Priuralye Hotel
4,Magdagachi,RU,2.53,53.45,125.80,Motopolyana Magdagachi
5,Inuvik,CA,3.20,68.36,-133.71,Nova Inn Inuvik
6,Thompson,CA,3.20,55.74,-97.86,Burntwood Hotel
7,Tuktoyaktuk,CA,3.20,69.44,-133.03,End of The Road Ltd.
8,Aklavik,CA,3.20,68.22,-135.01,Aklavik Inn
9,Motygino,RU,3.49,58.18,94.69,"Gostinitsa ""Uyut"""
10,Naryan-Mar,RU,4.28,67.67,53.09,Hostel Agat
11,Alta,NO,5.00,69.97,23.27,Scandic Alta
12,Iqaluit,CA,5.00,63.75,-68.52,Frobisher Inn
13,Pevek,RU,5.20,69.70,170.27,Munitsipal'naya Gostinitsa
14,Zhigansk,RU,5.94,66.77,123.37,Gostinichnyy Kompleks Aylgy
15,Fort Nelson,CA,6.80,58.81,-122.69,The Fort Nelson Hotel
16,Whitehorse,CA,6.80,60.72,-135.06,Westmark Hotel
17,Chernyshevskiy,RU,8.22,63.01,112.47,Chernyseyskiy
18,Okhotsk,RU,8.22,59.36,143.24,Gostinitsa V Okhotske
19,Vagamo,NO,8.22,61.88,9.10,Vågå hotel

In [15]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [18]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [19]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))